---
name: Testing

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: ./uv pip install --system -r requirements.test
    - name: pytest
      run: pytest -vvv
      env:
        PYTHONPATH: .
