---
name: HACS/HA

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: 0 0 * * *

jobs:
  hacs:
    name: HACS and Home assistant
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: home-assistant/actions/hassfest@master
    - name: HACS Action
      uses: hacs/action@main
      with:
        category: integration
