---
name: HA

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: 0 0 * * *

jobs:
  ha:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: home-assistant/actions/hassfest@master
