---
name: HACS

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: 0 0 * * *

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: HACS Action
      uses: hacs/action@main
      with:
        category: integration
