---
name: Integration tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: 2.26.1
    - name: Install dependencies
      run: ./uv pip install --system -r requirements.test
    - name: Integration tests
      run: cd integration_tests && python test_banning_works.py
