---
name: pre-commit

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        ./uv venv
        ./uv pip install -r requirements.test
    - name: pre-commit
      run: .venv/bin/pre-commit run -a
